/**
 *     Copyright 2015-2016 GetSocial B.V.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GetSocialGooglePlayGamesConstants
{
        public const string achievement_achievement_5 = "CggI3te5k3kQAhAF"; // <GPGSID>
        public const string achievement_achievement_1 = "CggI3te5k3kQAhAB"; // <GPGSID>
        public const string package_name = "im.getsocial.testapp.unity.master"; // <GPGSID>
        public const string achievement_achievement_2 = "CggI3te5k3kQAhAC"; // <GPGSID>
        public const string achievement_achievement_3 = "CggI3te5k3kQAhAD"; // <GPGSID>
        public const string achievement_achievement_4 = "CggI3te5k3kQAhAE"; // <GPGSID>

}

